#!/usr/bin/env php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use Minicli\App;
use Minicli\Exception\CommandNotFoundException;

$app = new App(config_default(__DIR__ . '/config'));
$app->setSignature('
     _    ___ ____     ___              _ _ _
    / \  |_ _|  _ \   / _ \ _   _  __ _| (_) |_ _   _
   / _ \  | || |_) | | | | | | | |/ _` | | | __| | | |
  / ___ \ | ||  _ <  | |_| | |_| | (_| | | | |_| |_| |
 /_/   \_\___|_| \_\  \__\_\\__,_|\__,_|_|_|\__|\__, |
                                                |___/
Type "./air-quality help" for help with available commands.');

try {
    $app->runCommand($argv);
} catch (CommandNotFoundException $notFoundException) {
    $app->getPrinter()->error("Command Not Found.");
    return 1;
} catch (Exception $exception) {
    if ($app->config->debug) {
        $app->getPrinter()->error("An error occurred:");
        $app->getPrinter()->error($exception->getMessage());
    }
    return 1;
}

return 0;
