name: Release

on:
    push:
        tags:
            - "v*"
    workflow_run:
      workflows: ["Tests"]
      branches: [main]
      types:
        - completed

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name.
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:

    release-github:
        name: Create GitHub Release with tag ${{ github.ref_name }}
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: "Checkout repository"
              uses: "actions/checkout@v3"

            - name: "Create Checksum SHA256 files"
              run: |
                zip -r ../air-quality-cli.zip .
                sha256sum air-quality-cli.zip > air-quality-cli_${{ github.ref_name }}_checksum.sha256

            - name: Create GitHub Release
              uses: ncipollo/release-action@v1.12.0
              with:
                artifacts: "air-quality-cli_${{ github.ref_name }}_checksum.sha256"
